# Generated by Django 3.2.6 on 2021-09-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year', models.CharField(choices=[('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029'), ('2030', '2030')], max_length=6)),
                ('link', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ClassTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('Математика', 'Математика'), ('Български език и литература', 'Български език и литература'), ('Английски език', 'Английски език'), ('Немски език', 'Немски език'), ('Испански език', 'Испански език'), ('Руски език', 'Руски език')], max_length=50)),
                ('date', models.DateField()),
                ('srok', models.CharField(choices=[('I срок', 'I срок'), ('II срок', 'II срок')], max_length=10)),
                ('klas', models.CharField(choices=[('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=50)),
                ('paralelka', models.CharField(choices=[('А', 'А'), ('Б', 'Б'), ('В', 'В'), ('Г', 'Г')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='HomePageMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=4096)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('important', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('portfolio', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('type', models.CharField(blank=True, choices=[('Ръководство', 'Ръководство'), ('Чужди езици', 'Чужди езици'), ('Природни науки', 'Природни науки'), ('Обществени науки', 'Обществени науки')], max_length=256, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='teachers')),
            ],
        ),
    ]
