# Generated by Django 3.2.6 on 2021-08-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_teacher_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('portfolio', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='teachers')),
            ],
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
