# Generated by Django 3.2.6 on 2021-08-04 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_publication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='name',
            new_name='title',
        ),
    ]
