# Generated by Django 3.2.6 on 2021-08-12 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_rename_name_publication_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year', models.CharField(choices=[('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029'), ('2030', '2030')], max_length=6)),
                ('link', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ClassTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('Математика', 'Математика'), ('Български език и литература', 'Български език и литература'), ('Английски език', 'Английски език'), ('Немски език', 'Немски език'), ('Испански език', 'Испански език'), ('Руски език', 'Руски език')], max_length=50)),
                ('date', models.DateField()),
                ('srok', models.CharField(choices=[('I срок', 'I срок'), ('II срок', 'II срок')], max_length=10)),
                ('klas', models.CharField(choices=[('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=50)),
                ('paralelka', models.CharField(choices=[('А', 'А'), ('Б', 'Б'), ('В', 'В'), ('Г', 'Г')], max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='homepagemessages',
            name='important',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
