# Generated by Django 3.2.6 on 2021-08-07 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_rename_name_publication_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagemessages',
            name='important',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
