# Generated by Django 3.2.6 on 2021-08-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20210812_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='type',
            field=models.CharField(blank=True, choices=[(0, 'Ръководство'), (1, 'Чужди езици'), (2, 'Природни науки'), (3, 'Обществени науки')], max_length=256, null=True),
        ),
    ]
