# Generated by Django 3.2.6 on 2021-08-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20210807_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('Математика', 'Математика'), ('Български език и литература', 'Български език и литература'), ('Английски език', 'Английски език'), ('Немски език', 'Немски език'), ('Испански език', 'Испански език'), ('Руски език', 'Руски език')], max_length=50)),
                ('date', models.DateField()),
                ('srok', models.CharField(choices=[('I срок', 'I срок'), ('II срок', 'II срок')], max_length=10)),
                ('klas', models.CharField(choices=[('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=50)),
                ('paralelka', models.CharField(choices=[('А', 'А'), ('Б', 'Б'), ('В', 'В'), ('Г', 'Г')], max_length=10)),
            ],
        ),
    ]
